#!/usr/bin/env python3
"""Build the source-attested MHC prefix registry shipped by mhcseqs.

The registry combines three kinds of evidence:

* current official species designations from the IPD-MHC taxonomy page;
* prefixes present in the retained UniProt source labels for the legacy
  diverse-MHC corpus; and
* explicitly curated historical nomenclature from primary papers and
  nomenclature reports.

Generated 2+2/4+4/5+5 spellings are deliberately not accepted merely because
they can be derived from a scientific name.
"""

from __future__ import annotations

import argparse
import csv
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_AUDIT = ROOT / "data" / "species_prefix_audit_pre_full_binomial.csv"
DEFAULT_OUTPUT = ROOT / "mhcseqs" / "mhc_prefix_aliases.csv"

IPD_TAXONOMY_URL = "https://www.ebi.ac.uk/ipd/mhc/taxonomy/"
KLEIN_1990_URL = "https://pubmed.ncbi.nlm.nih.gov/2329006/"
NHP_2019_URL = "https://www.eva.mpg.de/documents/Springer/Groot_Nomenclature_Immunogenetics_2020_3174021.pdf"

FIELDS = ["species", "prefix", "scope", "status", "evidence", "notes"]

# These are MHC descriptions, not species identifiers. Their occurrence in a
# source label therefore does not establish a species prefix.
GENERIC_SOURCE_LABELS = {"I", "MHC", "MHC II H2"}

# Current well-established system/group names which are not all exposed as
# species designations on the IPD taxonomy table.
SYSTEM_PREFIXES = [
    ("Homo sapiens", "HLA", "exact", "https://hla.alleles.org/genes/index.html"),
    ("Mus musculus", "H2", "exact", KLEIN_1990_URL),
    ("Rattus", "RT1", "genus", IPD_TAXONOMY_URL),
    ("Bos", "BoLA", "genus", IPD_TAXONOMY_URL),
    ("Sus", "SLA", "genus", IPD_TAXONOMY_URL),
    ("Equus", "ELA", "genus", IPD_TAXONOMY_URL),
    ("Ovis", "OLA", "genus", IPD_TAXONOMY_URL),
    ("Capra", "CLA", "genus", "https://pubmed.ncbi.nlm.nih.gov/8134633/"),
    ("Canis", "DLA", "genus", IPD_TAXONOMY_URL),
    ("Felis", "FLA", "genus", "https://pubmed.ncbi.nlm.nih.gov/2492667/"),
    ("Oryctolagus", "RLA", "genus", "https://pubmed.ncbi.nlm.nih.gov/32522857/"),
    ("Gallus gallus", "Gaga", "exact", IPD_TAXONOMY_URL),
    ("Salmo salar", "Sasa", "exact", IPD_TAXONOMY_URL),
    ("Danio rerio", "Dare", "exact", "https://pubmed.ncbi.nlm.nih.gov/18439319/"),
]

# Historical system names and superseded NHP designations. Punctuation is
# retained because these are spellings found in the literature, not aliases
# generated by mhcseqs.
HISTORICAL_PREFIXES = [
    ("Homo sapiens", "HL-A", "exact", "https://hla.alleles.org/pages/antigens/naming_hla_antigens/"),
    ("Mus musculus", "H-2", "exact", KLEIN_1990_URL),
    ("Gallus gallus", "B", "exact", "https://pubmed.ncbi.nlm.nih.gov/6763913/"),
    ("Spalax ehrenbergi", "Smh", "exact", KLEIN_1990_URL),
    ("Rattus norvegicus", "Ag-B", "exact", "https://doi.org/10.1016/S0026-0495(83)80010-9"),
    ("Rattus norvegicus", "AgB", "exact", "https://doi.org/10.1016/S0026-0495(83)80010-9"),
    ("Rattus norvegicus", "H-1", "exact", "https://doi.org/10.1016/S0026-0495(83)80010-9"),
    ("Rattus norvegicus", "RtH-1", "exact", "https://doi.org/10.1016/S0026-0495(83)80010-9"),
    ("Rattus norvegicus", "R-1", "exact", "https://doi.org/10.1016/S0026-0495(83)80010-9"),
    ("Cavia porcellus", "GPLA", "exact", "https://pmc.ncbi.nlm.nih.gov/articles/PMC2190138/"),
    ("Cavia porcellus", "GPL-A", "exact", "https://pmc.ncbi.nlm.nih.gov/articles/PMC2190138/"),
    ("Xenopus laevis", "XLA", "exact", "https://pubmed.ncbi.nlm.nih.gov/2653371/"),
    ("Xenopus laevis", "XL-A", "exact", "https://pubmed.ncbi.nlm.nih.gov/2653371/"),
    ("Canis", "DL-A", "genus", "https://pubmed.ncbi.nlm.nih.gov/4939370/"),
    ("Sus", "SL-A", "genus", "https://pubmed.ncbi.nlm.nih.gov/125631/"),
    ("Oryctolagus", "RL-A", "genus", "https://openalex.org/W2093336722"),
    ("Oryctolagus", "RbH-1", "genus", "https://openalex.org/W2093336722"),
    ("Bos", "BL-A", "genus", KLEIN_1990_URL),
    ("Pan troglodytes", "ChLA", "exact", NHP_2019_URL),
    ("Gorilla gorilla", "GoLA", "exact", NHP_2019_URL),
    ("Pongo pygmaeus", "OrLA", "exact", NHP_2019_URL),
    ("Macaca mulatta", "RhLA", "exact", NHP_2019_URL),
    ("Semnopithecus entellus", "Pren", "exact", NHP_2019_URL),
    ("Aotus trivirgatus", "OmLA", "exact", NHP_2019_URL),
    ("Callithrix jacchus", "MaLA", "exact", NHP_2019_URL),
    ("Callithrix pygmaea", "Cepy", "exact", NHP_2019_URL),
    (
        "Litoria verreauxii",
        "Livea",
        "exact",
        "https://pmc.ncbi.nlm.nih.gov/articles/PMC4389617/",
    ),
]

# Source-database labels found outside the retained raw-label prefix audit.
# These are accepted input aliases, but are not promoted to formal systems.
ADDITIONAL_DATABASE_PREFIXES = [
    (
        "Fringilla coelebs",
        "Frcoe",
        "exact",
        "https://www.ncbi.nlm.nih.gov/nuccore/DQ257477",
        "GenBank/retired UniProt gene label for the published chaffinch MHC-I fragment",
    ),
]


def _row(species: str, prefix: str, scope: str, status: str, evidence: str, notes: str = "") -> dict[str, str]:
    return {
        "species": species,
        "prefix": prefix,
        "scope": scope,
        "status": status,
        "evidence": evidence,
        "notes": notes,
    }


def parse_ipd_taxonomy(html_path: Path) -> list[dict[str, str]]:
    """Extract current official designations from a saved IPD taxonomy page."""
    text = html_path.read_text(encoding="utf-8")
    try:
        block = text.split("var organismList = [", 1)[1].split("];", 1)[0]
    except IndexError as exc:
        raise ValueError(f"Could not find IPD organismList in {html_path}") from exc

    pattern = re.compile(
        r"\{\s*'id':\d+, \"name\": \"(?P<name>[^\"]+)\", "
        r"\"common\": \"[^\"]*\", \"groupid\":\d+, \"group\": "
        r"\"(?P<group>[^\"]+)\",\"alias\": \"(?P<alias>[^\"]+)\","
        r"\"taxon\":(?P<taxon>\d+)\}"
    )
    result = []
    for match in pattern.finditer(block):
        values = match.groupdict()
        species = html.unescape(values["name"])
        raw_designation = html.unescape(values["alias"])
        prefixes = list(dict.fromkeys(re.findall(r"[A-Za-z][A-Za-z0-9-]*", raw_designation)))
        for prefix in prefixes:
            result.append(
                _row(
                    species,
                    prefix,
                    "exact",
                    "ipd_current",
                    IPD_TAXONOMY_URL,
                    f"IPD group={values['group']}; taxon={values['taxon']}; designation={raw_designation}",
                )
            )
    if len({row["species"] for row in result}) != 125:
        raise ValueError("Expected the current IPD taxonomy snapshot to contain 125 organisms")
    return result


def load_legacy_source_aliases(audit_path: Path) -> list[dict[str, str]]:
    """Load prefix spellings that occur in external source labels."""
    result = []
    with audit_path.open(encoding="utf-8") as handle:
        for audit_row in csv.DictReader(handle):
            if audit_row["status"] not in {
                "external_registry_or_literature",
                "external_uniprot_label",
            }:
                continue
            prefix = audit_row["legacy_prefix"]
            if prefix in GENERIC_SOURCE_LABELS:
                continue
            status = "external_database" if audit_row["status"] == "external_uniprot_label" else "formal_system"
            accessions = audit_row["example_accessions"]
            notes = (
                "attested in the retained source label for " + accessions if accessions else "source established by the cited registry or literature"
            )
            result.append(
                _row(
                    audit_row["species"],
                    prefix,
                    "exact",
                    status,
                    audit_row["evidence"],
                    notes,
                )
            )
    return result


def build_registry(audit_path: Path, ipd_html_path: Path) -> list[dict[str, str]]:
    """Combine, de-duplicate, and deterministically order registry rows."""
    rows = parse_ipd_taxonomy(ipd_html_path)
    rows.extend(load_legacy_source_aliases(audit_path))
    rows.extend(_row(species, prefix, scope, "formal_system", source) for species, prefix, scope, source in SYSTEM_PREFIXES)
    rows.extend(_row(species, prefix, scope, "literature_historical", source) for species, prefix, scope, source in HISTORICAL_PREFIXES)
    rows.extend(
        _row(species, prefix, scope, "external_database", source, notes) for species, prefix, scope, source, notes in ADDITIONAL_DATABASE_PREFIXES
    )

    priority = {
        "ipd_current": 0,
        "formal_system": 1,
        "literature_historical": 2,
        "external_database": 3,
    }
    selected: dict[tuple[str, str, str], dict[str, str]] = {}
    for row in rows:
        key = (row["species"].casefold(), row["prefix"].casefold(), row["scope"])
        previous = selected.get(key)
        if previous is None or priority[row["status"]] < priority[previous["status"]]:
            selected[key] = row
    return sorted(
        selected.values(),
        key=lambda row: (row["species"].casefold(), priority[row["status"]], row["prefix"].casefold()),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit", type=Path, default=DEFAULT_AUDIT)
    parser.add_argument("--ipd-html", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    rows = build_registry(args.audit, args.ipd_html)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} source-attested aliases to {args.output}")


if __name__ == "__main__":
    main()
